models:
  student: unsloth/Llama-3.2-1B-Instruct
  teacher: Qwen/Qwen2.5-1.5B-Instruct
data:
  name: IlyaGusev/saiga_scored
  sonnet_easy: true
  language: ru
train:
  epochs: 4
  inference_batch: 256
  accum_steps: 4
  lr: 3e-6

# Llama-3.2: 1B, 3B
# Qwen2.5: 0.5B, 1.5B, 7B
